name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  code_format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            distribution: zulu
            java: 8
          - os: ubuntu-latest
            distribution: temurin
            java: 11
          - os: ubuntu-latest
            distribution: temurin
            java: 17
          - os: windows-latest
            distribution: temurin
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "${{ matrix.distribution }}"
          java-version: "${{ matrix.java }}"
      - name: sbt scripted test
        run: ./sbt compile scripted
