name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  code_format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
  test_jdk11:
    name: Test JDK11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: sbt scripted test
        run: ./sbt compile scripted
  test_jdk17:
    name: Test JDK17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution:	'temurin'
          java-version:	17
      - name: sbt scripted test
        run: ./sbt compile scripted
