name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.sbt'
      - '.github/workflows/**.yml'
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.sbt'
      - '.github/workflows/**.yml'

jobs:
  code_format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
  test_jdk11:
    name: Test JDK11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: sbt scripted test
        run: ./sbt compile scripted
  test_jdk17:
    name: Test JDK17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution:	'temurin'
          java-version:	17
      - name: sbt scripted test
        run: ./sbt compile scripted
